---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-deployment
  labels:
    app: toad
spec:
  replicas: 4
  selector:
    matchLabels:
      app: toad
  template:
    metadata:
      labels:
        app: toad
    spec:
      containers:
      - name: toad
        image: clivern/toad:release-0.1.5
        ports:
        - containerPort: 8080