---
apiVersion: v1
kind: Service
metadata:
  name: toad-loadbalancer
  labels:
    app: toad
    tier: backend
    app.clivern.com/managed-by: beetle
spec:
  ports:
    -
      port: 80
      targetPort: 8080
  selector:
    app: toad
    tier: backend
    deployment: blue # Old version
  type: LoadBalancer
