---
apiVersion: v1
kind: Service
metadata:
  name: toad-loadbalancer
  labels:
    app: toad
    tier: backend
spec:
  ports:
    -
      port: 80
      targetPort: 8080
  selector:
    app: toad
    tier: backend
    deployment: green # New version
  type: LoadBalancer
